spring.application.name=Eureka

server.port=${SERVER_PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=7

management.tracing.sampling.probability=1.0
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
