spring.application.name=UserService

userservice.service-token=${USER_SERVICE_TOKEN}


jwt.secret=${JWT_SECRET}
spring.datasource.url = jdbc:postgresql://localhost:5432/userprofileinfodb
spring.datasource.username=faysonin
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8092
logging.level.org.springframework.security=DEBUG

spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest

spring.rabbitmq.template.exchange=userauth.exchange
spring.rabbitmq.template.default-receive-queue=userauth.queue
spring.rabbitmq.template.routing-key=userauth.tracking