global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8090']
        labels:
          application: 'ApiGateway'

  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']
        labels:
          application: 'Eureka'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8091']
        labels:
          application: 'AuthService'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8092']
        labels:
          application: 'UserService'

  - job_name: 'ai-image-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ai-image-service:8093']
        labels:
          application: 'AiImageService'

  - job_name: 'recipe-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recipe-service:8094']
        labels:
          application: 'RecipeService'

  - job_name: 'household-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['household-service:8096']
        labels:
          application: 'HouseholdService'

  - job_name: 'recipes-from-db-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recipes-from-db-service:8095']
        labels:
          application: 'RecipesFromDbService'
