spring.application.name=AiImageService
server.port=8093

spring.threads.virtual.enabled=true


userservice.service-token=${USER_SERVICE_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5432/foodanalysis
spring.datasource.username=faysonin
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.aws.s3.endpoint=https://s3.eu-central-003.backblazeb2.com
spring.cloud.aws.region.static=eu-central-003
spring.cloud.aws.credentials.access-key=${S3_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${S3_SECRET_KEY}

application.bucket.name=Bucket193134
application.bucket.public-url=https://f003.backblazeb2.com/file/Bucket193134

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
server.tomcat.max-http-form-post-size=10MB


spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.template.exchange=food.analysis.exchange
spring.rabbitmq.template.default-receive-queue=food.analysis.queue
spring.rabbitmq.template.routing-key=food.analysis.tracking

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
#spring.ai.google.genai.chat.options.model=gemini-3-pro-preview
spring.ai.google.genai.project-id=${GEMINI_PROJECT_ID}
spring.ai.google.genai.location=us-central1
#logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=7

management.tracing.sampling.probability=1.0
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*