spring.application.name=RecipesFromDbService
server.address=0.0.0.0
server.port=${SERVER_PORT:8095}

spring.threads.virtual.enabled=true

jwt.secret=${JWT_SECRET}
userservice.service-token=${USER_SERVICE_TOKEN}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recipes}
spring.jpa.properties.hibernate.default_schema=${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:cookbook_wh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.compression.enabled=true
server.compression.min-response-size=1024
spring.mvc.async.request-timeout=60000

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${HOSTNAME:${random.value}}

logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=7

management.tracing.sampling.probability=1.0
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
